## Array Indexing
Array indexing is nothing but it is simply accessing the array of the numpy array.
The values of the numpy array 'x' can be accessed by using the index 'i' as x\[i\].
Below is the example:-

In [1]:
import numpy as np
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(x[5])

5


For accessing the value from the 2d array we use the comma-separated index i, j as rows and column values respectively.

In [4]:
x = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2st row: ', x[1, 4])

5th element on 2st row:  10


And similarly, for accessing the 3d array we use comma-separated indexes i, j, k representing the dimensions of the array. below is the example:-

In [5]:
x = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(x[0, 1, 2])

6


## Array Slicing:-
In NumPy, Slicing is a process of extracting the values between the given indexes from the NumPy arrays.
Slicing is done by passing the index values inside the square bracket with a semicolon like this \[start:end\] and we can also give steps like \[start:end:step].

In [7]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(x[1:7])

[2 3 4 5 6 7]


In [8]:
x = np.array([2, 3, 5, 6, 7, 9, 10])
print(x[:3])

[2 3 5]


In [9]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
print(x[1:5:2])

[2 4]


For Slicing in 2d NumPy array, we use comma-separated slicing indexes like

In [10]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(x[1, 1:3])

[7 8]


In [11]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(x[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## Memory Layout of ndarray:-
In memory, ndarray are stored as contiguous data. We have freedom of choice in how to arrange the array elements in this memory segment. Consider the case of a two-dimensional array, containing rows and columns:
The former is called row-major format and the latter is column-major format.
A NumPy array can be stored in the row-major format, using the keyword argument order='C', and in the column-major format, using the keyword argument order='F'.

In [12]:
xc = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                dtype='uint8', order='C')
xf = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                dtype='uint8', order='F')

In [13]:
xc

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=uint8)

In [15]:
'  '.join(str(x) for x in np.nditer(xc))

'1  2  3  4  5  6  7  8  9'

In [14]:
xf

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=uint8)

In [16]:
'  '.join(str(x) for x in np.nditer(xf))

'1  4  7  2  5  8  3  6  9'

## Views and Copies:-
Copy is just the new copy of the original array. Any change to the copy will not affect the original array and any change done in the original will not affect the copy.
While View is only the view of the original array it does not own the, if we make a change in the original array, it also reflects in view.


In [18]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])
x = array.copy()
array[1] = 42

print(array)
print(x)

[10 42 30 40 50]
[10 20 30 40 50]


In [19]:
array = np.array([10, 20, 30, 40, 50])
x = array.view()
array[1] = 42

print(array)
print(x)

[10 42 30 40 50]
[10 42 30 40 50]


## Creating Array and Array Data type:-
The array is created in NumPy by using the array() function. And to get the data type of the array we use the type() function.

In [21]:
array = np.array([1, 2, 3, 4, 5])
print(array)
print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Linear Algebra:-

In [2]:
import numpy as np
arr = np.array([[1,2], [3,4]]) 
print (np.linalg.det(arr))

-2.0000000000000004


In [3]:
import numpy.matlib 
import numpy as np 

a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [5]:
a = np.array([[1,2],[3,4]]) 
b = np.linalg.inv(a) 
print(a) 
print(b) 

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
import numpy as np
import timeit

print(np.sum(np.arange(15000)))  
print("Time taken by vectorized sum : ", end = "")
%timeit np.sum(np.arange(15000))

112492500
Time taken by vectorized sum : 89.2 µs ± 11 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
total = 0
for item in range(0, 15000):
    total += item
a = total
print("\n" + str(a))
  
print("Time taken by iterative sum : ", end = "")
%timeit a


112492500
Time taken by iterative sum : 138 ns ± 20.8 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


## Shape Manipulation

In [8]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## Boolean Masking:-

In [9]:
x = np.array([1,3,-1, 0, 7, -1]) 
mask = (x <= 0) 
mask 

array([False, False,  True,  True, False,  True])

In [10]:
x [mask] = 0 
x 

array([1, 3, 0, 0, 7, 0])

In [11]:
import datetime

x = datetime.datetime.now()
print(x)

2021-07-01 01:21:47.782445


In [12]:
import numpy as np
date = np.array(np.datetime64('2021-07-01', 'D'))
print(date)

2021-07-01
