# The Scientific python - Scipy

In python, scipy is an open source scientific computation library that uses Numpy. It provodes convenient and fastes N-dimensional array manuplation. It is used for solving scientific, mathematical and engineering related problem statements. It also provides utility functions for optimization, stats and signal processing. You must have thought that why scipy? we have Numpy for this stuff. So the answer for your this question is that the scipy provides more optimized and added functionalities that are frequently used in Numpy and Data Science. NumPy provides a number of functions that can help resolve linear algebra, Fourier transforms, etc, but SciPy is the library that actually contains fully-featured versions of all these functions along with many others scientific features.

## Installation and import:-

In [2]:
!pip install scipy

In [5]:
from scipy import cluster 
help(cluster) #with parameter 

Help on package scipy.cluster in scipy:

NAME
    scipy.cluster

DESCRIPTION
    Clustering package (:mod:`scipy.cluster`)
    
    .. currentmodule:: scipy.cluster
    
    :mod:`scipy.cluster.vq`
    
    Clustering algorithms are useful in information theory, target detection,
    communications, compression, and other areas. The `vq` module only
    supports vector quantization and the k-means algorithms.
    
    :mod:`scipy.cluster.hierarchy`
    
    The `hierarchy` module provides functions for hierarchical and
    agglomerative clustering.  Its features include generating hierarchical
    clusters from distance matrices,
    calculating statistics on clusters, cutting linkages
    to generate flat clusters, and visualizing clusters with dendrograms.

PACKAGE CONTENTS
    _hierarchy
    _optimal_leaf_ordering
    _vq
    hierarchy
    setup
    tests (package)
    vq

DATA
    __all__ = ['vq', 'hierarchy']

FILE
    c:\users\sk620\appdata\local\programs\python\python38\lib\site

## Exponential and Trigonometric Functions:

In [7]:
from scipy import special
x = special.exp10(5)    # Gives exponents
print(x)
 
y = special.sindg(90)    # Gives Sine value of 90 degree
print(y)
 
d = special.cosdg(45)    # Gives cosine value of 45 degree
print(d)

100000.0
1.0
0.7071067811865475


In [2]:
from scipy import constants

# gives pi value.
print(constants.pi)

# gives metric prefixes in meters
print(constants.zetta)    #1e+21
print(constants.exa)      #1e+18
print(constants.giga)     #1000000000.0
print(constants.mega)     #1000000.0
print(constants.kilo)     #1000.0
print(constants.hecto)    #100.0

# gives times in seconds
print(constants.minute)
print(constants.day)

# gives Angles in Radian
print(constants.degree)

# gives pressure in pascals
print(constants.atm)
print(constants.bar) 

3.141592653589793
1e+21
1e+18
1000000000.0
1000000.0
1000.0
100.0
60.0
86400.0
0.017453292519943295
101325.0
100000.0


In [1]:
import numpy as np
from scipy.sparse.csgraph import dijkstra
from scipy.sparse import csr_matrix

arr = np.array([
  [0, 1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(dijkstra(newarr, return_predecessors=True, indices=1))

# return_predecessors: takes boolean(True to return whole path of traversal otherwise False).
# indices: index of the element to return all paths from that element only.

(array([1., 0., 3.]), array([    1, -9999,     0]))


In [4]:
import numpy as np
from scipy.sparse.csgraph import bellman_ford
from scipy.sparse import csr_matrix

arr = np.array([
  [0, -1, 2],
  [1, 0, 0],
  [2, 0, 0]
])

newarr = csr_matrix(arr)

print(bellman_ford(newarr, return_predecessors=True, indices=2))

(array([2., 1., 0.]), array([    2,     0, -9999]))


## Linear Algebra:-

In [6]:
import numpy as np
from scipy import linalg

A = np.array([[1,2,3],[4,5,6],[7,8,8]])
linalg.det(A) # Find the determinant of a matrix.

3.0

In [7]:
eigen_values, eigen_vectors = linalg.eig(A)
print(eigen_values)   # Gives Eigen Value
print(eigen_vectors)  # Gives Eigen Vector

[15.55528261+0.j -1.41940876+0.j -0.13587385+0.j]
[[-0.24043423 -0.67468642  0.51853459]
 [-0.54694322 -0.23391616 -0.78895962]
 [-0.80190056  0.70005819  0.32964312]]


## Integration:-

In [8]:
import scipy.integrate
f= lambda x:np.exp(-x**2)
i = scipy.integrate.quad(f, 0, 1) # Gives Single Integrations
print(i) 

(0.7468241328124271, 8.291413475940725e-15)


In [9]:
from scipy import integrate
f = lambda y, x: x*y**2
i = integrate.dblquad(f, 0, 2, lambda x: 0, lambda x: 1) 
print(i) # Gives Double Integrations

(0.6666666666666667, 7.401486830834377e-15)
